### ISSUE TITLE
Simulight Plugin broken

### ISSUE THREAD

**Issue by FullPace** [SHWotever/SimHub#1661]
Hi, the Govee Light Bars not found any more and log throws error every ms.
Thank you in advance! 
![image](https://github.com/user-attachments/assets/550703ba-bb00-4451-957a-5d29b0d8e147)
[SimHub.2.txt](https://github.com/user-attachments/files/16553575/SimHub.2.txt)

**Comment by SHWotever** [comment]
Hi ! I checked and I think I found the hole which would have allowed this to happen. Its fixed for the next version.

**Comment by FullPace** [comment]
hi, thanks for the effort but unfortunately the error is still persistent.
I just installed 9.04.2 and its still flooding the logfiles
![image](https://github.com/user-attachments/assets/c8bd5627-88f9-464c-a993-274cdbf8dc11)

**Comment by SHWotever** [comment]
Hi !

I think I got it now, I've published a las patch ! Fingers crossed !

**Comment by FullPace** [comment]
🤞

**Comment by FullPace** [comment]
unfortunately still the same behaviour in the latest version
![image](https://github.com/user-attachments/assets/286e06f3-d919-4222-a80f-42b47f7e8e1f)

**Comment by SHWotever** [comment]
Hi ! Can you send me the full log file ? This is really weird as an error at this location is not supposed to be able to happen now (even if I fixed code which could have been the cause) I did ensure that it could not happen here.

**Comment by FullPace** [comment]
Hi, I started the rig computer a few times and the error did not appear again. I don't know why it still acted weird last time but I think it's working now again. thanks!
