### ISSUE TITLE
Adafruit HT16K33 8x8 intensity setting oddities

### ISSUE THREAD

**Issue by sjdawson** [SHWotever/SimHub#512]
Using an HT16K33 from Adafruit, whenever you close and relaunch SimHub, the 8x8 LED matrix starts with an intensity of 0/1, regardless of what is set in SimHub.

Steps:
* With an Arduino connected, running an 8x8 HT16K33 Matrix
* Set the main "Matrix Intensity" to it's highest value, 16
* Close SimHub, then reopen it.
* Play a game/replay - the Matrix will be at it's lowest intensity (dark)

I've also noticed that changing the intensity in settings, the actual display is 1 behind what was set. For example, go to the lower end of the scale 3->2->1->0, when you hit 0, you're actually at intensity 1. When you go back _up_ to intensity 1, you'll see the matrix dim again down to 0.

**Comment by SHWotever** [comment]
Hi ! I fixed it for the next release. Indeed there was a big big about brightness.

**Comment by sjdawson** [comment]
> Hi ! I fixed it for the next release. Indeed there was a big big about brightness.

Thank you :)

**Comment by sjdawson** [comment]
On the latest version, 7.0.1, this issue is still present.

There's a quicker way to recreate the problem:

* Start watching a replay
* Go back to live mode
* Change game to something else in SimHub
* Return to the game you were watching the replay of
* Start the replay

The intensity of the matrix will be at it's lowest, despite being set quite high.

**Comment by SHWotever** [comment]
Hello ! Have you reupload the sketch ? The bug was in the Arduino code.
Let me know.

**Comment by sjdawson** [comment]
Oooo! Sorry, didn't realise that was the case. Will re-upload and reply in a few mins.

**Comment by SHWotever** [comment]
No worries, I should have specified it 😨

**Comment by sjdawson** [comment]
Spot on. Problem solved! 🕵️
