### ISSUE TITLE
Nextion Display not responsive

### ISSUE THREAD

**Issue by TerryP9** [SHWotever/SimHub#814]
Hello,

I created my own dashboard (not my first time) and this time I used a Nextion 4.3 **enhanced (NX4827T043)** instead.

Now the Arduino micro works properly because I am able to assign the controls with the buttons on my dashboard. Also, I pushed the TFT file with the SD card and the IDLE screen is the good one.

I did the mapping and saved the file as well. Everything is where it should be.

Now in Simhub under Nextion display / Nextion #1 I can see the FPS around 9.0 telling me the display it connected correctly.

My problem is that the screen just don't show up with the mapped information i.e. I added a clock on the idle screen and it stays still at 00:00:00
Same in-game, nothing changes and it stays on the Idle screen.

I would really appreciate some help here.

Thank you!
Thierry

**Comment by Jorin-Post** [comment]
Hello Thierry,
You can debug on the Nextion Editor with the Arduino by using UMC input  com.. 
If the upload from Simhub is successful it should work in the debug window.
So far I know if everything is uploaded correct on the Nextion it will start as soon as it gets data from the RT.

If it still doesn't work I can take a look at the Nextion code and the Arduino code.
Hope this helps,
Jorin

**Comment by TerryP9** [comment]
Hi Jorin,

Thank you for your answer this is very appreciated.

So I tried with a non Enhanced version of the Nextion 4.3 and everything worked flawlessly.

Now I'm starting to think that it might be the source of my problem (the Enhanced version), am I wrong?

Everything is indeed uploaded correctly to the Nextion and It looks like I just don't get any data... My RX goes to my TX and my TX to Rx...

Any idea?
Thanks!

**Comment by Jorin-Post** [comment]
Maybe...
Did you change the Nextion device settings to Enhanced?

**Comment by TerryP9** [comment]
Yes I did
I also tried with a second Enhanced that I have in case there was an issue with the connector and nothing changed, same issue

**Comment by Jorin-Post** [comment]
So far I know there is no difference besides the specs and the settings.
Does the program work in the debug function?

**Comment by SHWotever** [comment]
Hi ! I would check that the template required code is present : https://github.com/SHWotever/SimHub/wiki/Nextion-Display---Template-creation-using-mapping-editor#configure-the-template-to-talk-correcty-with-simhub

Are you able to upload with the embedded nextion uploader ? You said you used a micro SD, but if upload does not work it means something is wrong with the wiring. Simhub may appear connected but if the data is lost "on the wires" the screen won't react.

**Comment by TerryP9** [comment]
Yeah, I found it odd that the Enhanced will not work since it is possible to use different Nextion models in size without issues.
The program is good in Nextion, I compile and there are no errors. It works with the Standard one and I pushed the same in the Enhanced I just selected this model instead here (see above) 
It does work otherwise I would have added an error message
![image](https://user-images.githubusercontent.com/78366785/117329360-93861c80-ae62-11eb-940c-5863818285c4.png)

So this is what happens, this is the 4.3 Standard (work perfectly)"
![Image from iOS (117)](https://user-images.githubusercontent.com/78366785/117328977-2bcfd180-ae62-11eb-80b6-2ae0f3cfca75.jpg)
Here is the Enhanced one 
![Image from iOS (118)](https://user-images.githubusercontent.com/78366785/117329002-32f6df80-ae62-11eb-9f49-e4a7eb66306c.jpg)

As you can see, no data but I see the screen is recognized in SimHub:
![image](https://user-images.githubusercontent.com/78366785/117329183-633e7e00-ae62-11eb-969d-d55ecd388a3d.png)

**Comment by SHWotever** [comment]
Enhanced should not be an issue, but default baudrate is if you forgot the required code inside the template. So the screen might use an unsupported baudrate (and so not receive the sent data). Let me know if those instructions are correctly present in the template ( https://github.com/SHWotever/SimHub/wiki/Nextion-Display---Template-creation-using-mapping-editor#configure-the-template-to-talk-correcty-with-simhub)

**Comment by TerryP9** [comment]
I tried to push the same code in another display and got this error 
![image](https://user-images.githubusercontent.com/78366785/117331696-0395a200-ae65-11eb-9e6d-266ba5b01457.png)

**Comment by SHWotever** [comment]
Probably, that said this requirement exists since the early nextions so I never analyzed what was the default baudrate coming out from factory. It can be reprogrammed at anytime that's why adding it in the template was the safest way to ensure its always correct as soon as template is uploaded.
